version: '3'

services:
  fastapi_rtcserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
