version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
    restart: unless-stopped
    container_name: fastapi_rtcserver
