import type { Metadata } from "next";
import "./globals.css";
import ClientLayout from "./clientlayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ClientLayout />
        <div
          className="flex flex-col"
        >{children}</div>
      </body>
    </html>
  );
}
